[build]
rustflags = [
    "-C", "relocation-model=static",
    "-C", "link-args=--image-base=0xffffffff80100000 -z separate-code",
]
target = "x86_64-unknown-none.json"

[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]
