[build]
target = "wasm32-unknown-unknown"

[target.wasm32-unknown-unknown]
rustflags = [
  "-C",
  "link-args=-z stack-size=32768 --no-check-features",
  "-C",
  "target-feature=+bulk-memory,+nontrapping-fptoint,+sign-ext",
]
