
[workspace]
members = [
  "bball",
  "cube",
  "hello1",
  "hello2",
  "kray",
  "life",
  "noiz2bg",
  "tube",
]

[profile.release]
lto = true
opt-level = "z"

[workspace.dependencies]
megstd = { path = "../lib/megstd" }
libm = { features = ["unstable"] }
